export const apiKey = "5906a02aa1d34de283312224240610";

export const weatherImages = {
  "Partly cloudy": require("../assets/images/partlycloudy.png"),
  "Moderate rain": require("../assets/images/moderaterain.png"),
  "Patchy rain possible": require("../assets/images/moderaterain.png"),
  "Patchy snow possible": require("../assets/images/snow.png"),
  "Patchy sleet possible": require("../assets/images/sleet.png"),
  "Patchy freezing drizzle possible": require("../assets/images/freezingdrizzle.png"),
  "Thundery outbreaks possible": require("../assets/images/thunder.png"),
  "Blowing snow": require("../assets/images/blowingsnow.png"),
  "Blizzard": require("../assets/images/blizzard.png"),
  "Fog": require("../assets/images/fog.png"),
  "Freezing fog": require("../assets/images/freezingfog.png"),
  "Heavy freezing fog": require("../assets/images/freezingfog.png"),
  Sunny: require("../assets/images/sun.png"),
  Clear: require("../assets/images/sun.png"),
  "Partly sunny": require("../assets/images/partlycloudy.png"),
  Overcast: require("../assets/images/cloud.png"),
  Cloudy: require("../assets/images/cloud.png"),
  "Light rain": require("../assets/images/moderaterain.png"),
  "Patchy light drizzle": require("../assets/images/drizzle.png"),
  "Light drizzle": require("../assets/images/drizzle.png"),
  "Light sleet": require("../assets/images/sleet.png"),
  "Light snow": require("../assets/images/snow.png"),
  "Moderate snow": require("../assets/images/snow.png"),
  "Heavy snow": require("../assets/images/snow.png"),
  "Moderate rain at times": require("../assets/images/moderaterain.png"),
  "Heavy rain": require("../assets/images/heavyrain.png"),
  "Heavy rain at times": require("../assets/images/heavyrain.png"),
  "Moderate or heavy freezing rain": require("../assets/images/freezingrain.png"),
  "Moderate or heavy rain shower": require("../assets/images/heavyrain.png"),
  "Moderate or heavy rain with thunder": require("../assets/images/thunder.png"),
  "Light freezing rain": require("../assets/images/freezingrain.png"),
  "Heavy freezing drizzle": require("../assets/images/freezingdrizzle.png"),
  "Patchy light rain with thunder": require("../assets/images/thunder.png"),
  "Moderate or heavy snow showers": require("../assets/images/snow.png"),
  "Light snow showers": require("../assets/images/snow.png"),
  Mist: require("../assets/images/mist.png"),
  "Patchy light snow": require("../assets/images/snow.png"),
  "Patchy moderate snow": require("../assets/images/snow.png"),
  "Patchy heavy snow": require("../assets/images/snow.png"),
  "Ice pellets": require("../assets/images/icepellets.png"),
  "Moderate or heavy showers of ice pellets": require("../assets/images/icepellets.png"),
  "Patchy light rain": require("../assets/images/moderaterain.png"),
  "Patchy rain nearby": require("../assets/images/moderaterain.png"),
  "Patchy moderate rain": require("../assets/images/moderaterain.png"),
  "Patchy heavy rain": require("../assets/images/heavyrain.png"),
  "Light showers of ice pellets": require("../assets/images/icepellets.png"),
  "Light rain shower": require("../assets/images/moderaterain.png"),
  "Moderate or heavy sleet showers": require("../assets/images/sleet.png"),
  "Light sleet showers": require("../assets/images/sleet.png"),
  "Torrential rain shower": require("../assets/images/heavyrain.png"),
  "Hail showers": require("../assets/images/hail.png"),
  "Light hail": require("../assets/images/hail.png"),
  "Moderate hail": require("../assets/images/hail.png"),
  "Heavy hail": require("../assets/images/hail.png"),
  "Light snow grains": require("../assets/images/snow.png"),
  "Moderate snow grains": require("../assets/images/snow.png"),
  "Heavy snow grains": require("../assets/images/snow.png"),
  other: require("../assets/images/moderaterain.png"),
};
